##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.0.0] date: [Tue Oct 01 17:01:56 EAT 2019]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Name_task


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/ADC.c \
Src/GPIO.c \
Src/SysClock.c \
Src/SysControl.c \
Src/UART.c \
Src/SPI.c \
Src/Variable.c \
Src/Timers.c \
Src/Service.c \
Src/interrupts.c \
Drivers/STM32F10x_StdPeriph_Driver/src/misc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c \
Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c \
Drivers/CMSIS/CM3/DeviceSupport/ST/STM32F10x/system_stm32f10x.c

# ASM sources
ASM_SOURCES =  \
Device/startup_stm32f103xb.s



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DSTM32F103xB \
-DSTM32F10X_MD

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc\
-IDevice \
-IDrivers/STM32F10x_StdPeriph_Driver/inc \
-IDrivers/CMSIS/CM3/CoreSupport \
-IDrivers/CMSIS/CM3/DeviceSupport/ST/STM32F10x


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = Device/STM32F103CBTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
	# -rm -fR $(BUILD_DIR) //Linux ver
	# 	del /q $(BUILD_DIR) //Windows
#######################################
clean:
	del /q $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***